# irsa-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-service-account
  namespace: buildify
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377135844:role/phexhub-dev-cluster-ecr-service-account-role
