name: Feature request
description: Suggest an idea for this project
title: ''
labels: ['feature']
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Provide a clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: Provide a clear and concise description of what you want to happen.
      placeholder: I would like to...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Provide a clear and concise description of any alternative solutions or features you've considered.
      placeholder: I also considered...
    validations:
      required: false
  - type: textarea
    id: scope
    attributes:
      label: Feature Scope
      description: Describe the scope and impact of this feature.
      placeholder: This feature would affect...
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Here's a screenshot/mockup of what I have in mind...
    validations:
      required: false
