name: Feature
description: A pretty vague description of how a capability of our software can be added or improved.
title: ''
labels: ['feature']
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What capability should be either established or improved? How is life of the target audience better after it's been done?
      placeholder: This feature would improve the user experience by...
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: This is kind-of the definition-of-done for a feature. Try to keep the scope as small as possible and prefer creating multiple, small features which each solve a single problem / make something better.
      placeholder: |
        This feature will include:
        - Component A
        - Component B
        - Component C

        It will NOT include:
        - Unrelated feature X
        - Unrelated feature Y
    validations:
      required: true
  - type: textarea
    id: options
    attributes:
      label: Implementation Options
      description: If you already have an idea how this can be implemented, please describe it here. This allows potential other contributors to join forces and provide meaningful feedback prior to even starting work on it.
      placeholder: I think this could be implemented by...
    validations:
      required: false
  - type: textarea
    id: related
    attributes:
      label: Related
      description: Link to the epic or other issues or PRs which are related to this feature.
      placeholder: |
        - Epic: #123
        - Related: #456
        - Depends on: #789
    validations:
      required: false
