name: Setup GitHub CLI
description: Setup GitHub CLI with authentication
inputs:
  token:
    required: true
    type: string
    description: GitHub token for authentication

runs:
  using: composite

  steps:
    - name: Install GitHub CLI
      shell: bash
      run: |
        if ! command -v gh &> /dev/null; then
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
        fi

    - name: Authenticate GitHub CLI
      shell: bash
      run: |
        echo "${{ inputs.token }}" | gh auth login --with-token
        gh auth setup-git
