# filepath: /Users/nirmalarya/Workspace/buildify/k8s/backup/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: buildify-secrets
  namespace: buildify
type: Opaque
data:
  # These are placeholders. In a real environment, replace with actual base64-encoded values
  # or use a secret management solution like Sealed Secrets, Vault, or AWS Secrets Manager
  # Example: echo -n "your-api-key" | base64
  GROQ_API_KEY: ""
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  GOOGLE_GENERATIVE_AI_API_KEY: ""
  TOGETHER_API_KEY: ""
  AWS_BEDROCK_CONFIG: ""
