# filepath: /Users/nirmalarya/Workspace/buildify/k8s/backup/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: buildify-user-provider-secrets
  namespace: buildify
type: Opaque
data:
  # User-configurable API keys for various LLM providers
  # These keys can be set through the application frontend by users
  # and are NOT managed by AWS Secrets Manager
  #
  # Authentication secrets (SESSION_SECRET, GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET)
  # are managed separately through AWS Secrets Manager via ExternalSecret
  #
  # These are placeholders. In production, they will be populated by user input
  # through the application settings UI.
  # Example: echo -n "your-api-key" | base64
  
  # LLM Provider API Keys - User Configurable
  GROQ_API_KEY: ""
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  GOOGLE_GENERATIVE_AI_API_KEY: ""
  TOGETHER_API_KEY: ""
  AWS_BEDROCK_CONFIG: ""
  BAYER_MGA_API_KEY: ""
  MISTRAL_API_KEY: ""
  COHERE_API_KEY: ""
  PERPLEXITY_API_KEY: ""
  XAI_API_KEY: ""
  
  # Note: This secret only contains user-configurable provider API keys
  # Infrastructure-level authentication secrets are stored in AWS Secrets Manager
  # and injected via the buildify-auth-secrets ExternalSecret
