name: Prebuild for Render
on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'   # cache npm; pnpm will still be ok

      - name: Increase Node memory
        run: echo "NODE_OPTIONS=--max-old-space-size=2048" >> $GITHUB_ENV

      - name: Install deps (supports pnpm or npm)
        run: |
          if [ -f pnpm-lock.yaml ]; then
            npm i -g pnpm
            pnpm install --no-frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi

      - name: Build
        run: npm run build

      # Collect built assets into /dist for Render Static Site
      - name: Prepare static artifacts
        run: |
          rm -rf dist
          mkdir -p dist
          if [ -d build/client ]; then cp -R build/client/* dist/; fi
          if [ -d build/public ]; then cp -R build/public/* dist/; fi
          if [ -d app/public ]; then cp -R app/public/* dist/; fi
          # fallback: many Vite apps emit to "dist" already; leave as-is if present

      - name: Commit build artifacts
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add -f dist
          git commit -m "chore: add prebuilt dist for Render" || echo "Nothing to commit"
          git push

