name: Prebuild for Render

on:
  workflow_dispatch: {}         # allow manual runs
  push:
    branches: [ main ]          # also run on pushes to main

permissions:
  contents: write               # needed to push the prebuilt branch

concurrency:
  group: prebuild-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # we are going to create/force-push a branch

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9            # matches current pnpm major used by most Vite templates

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Increase Node memory
        run: |
          echo "NODE_OPTIONS=--max-old-space-size=1536" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build (Vite)
        env:
          # Avoid accidental dev-server behaviors
          NODE_ENV: production
        run: pnpm run build

      # At this point Vite should have produced ./dist
      - name: Verify dist exists
        run: |
          test -d dist || { echo "dist/ not found; check your build outputDir"; exit 1; }
          ls -lah dist | head -n 50

      - name: Publish dist to render-build branch
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B render-build
          # keep only dist in this branch
          find . -mindepth 1 -maxdepth 1 ! -name dist ! -name .git -exec rm -rf {} +
          git add -f dist
          git commit -m "Prebuild for Render: ${GITHUB_SHA}" || echo "No changes to commit"
          git push -f origin render-build
