name: Prebuild for Render

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # we need full history to create/force-push a branch

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Increase Node memory
        run: echo "NODE_OPTIONS=--max-old-space-size=6144" >> $GITHUB_ENV

      - name: Build (Vite/Remix)
        run: pnpm run build

      # 👇 The client build ends up in build/client (not dist)
      - name: Verify client build exists
        run: |
          test -d build/client && ls -la build/client

      - name: Publish client build to render-build branch
        run: |
          OUT=build/client
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # stage files in a temp dir to avoid polluting the worktree
          rm -rf /tmp/render-build
          mkdir -p /tmp/render-build
          cp -R "$OUT"/. /tmp/render-build/

          # create/switch to branch that Render will serve
          git switch -C render-build

          # wipe branch contents and replace with prebuilt assets
          git rm -r --cached . >/dev/null 2>&1 || true
          git clean -fdx || true
          rm -rf ./* .[^.]* || true
          cp -R /tmp/render-build/. .

          git add -A
          git commit -m "Publish prebuilt client from $GITHUB_SHA" || echo "Nothing to commit"
          git push -f origin render-build
