name: Prebuild for Render

on:
  workflow_dispatch:   # run it manually from the Actions tab

permissions:
  contents: write      # allow the workflow to push a commit

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci --legacy-peer-deps

      - name: Build (more memory)
        run: |
          export NODE_OPTIONS="--max-old-space-size=3072"
          npm run build

      - name: Commit build artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A build dist || true
          if ! git diff --cached --quiet; then
            git commit -m "ci: prebuild assets for Render"
            git push
          else
            echo "No build changes to commit."
          fi
