name: Prebuild for Render
on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed so we can push back to repo

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      # If your build output is 'dist', change build/client to dist
      - name: Collect static output
        run: |
          rm -rf out && mkdir -p out
          cp -r build/client/* out/

      - name: Publish to stable branch
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git checkout -B stable
          rm -rf ./*
          cp -r out/* .
          git add -A
          git commit -m "Publish prebuilt site" || echo "nothing to commit"
          git push -f origin stable

