name: Add new PRs to Project (Current Cycle)

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: read
  repository-projects: write

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Authenticate gh
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Add PR to project
        run: |
          gh project item-add ${{ vars.PROJECT_ID }} --owner stackblitz-labs --url "${{ github.event.pull_request.html_url }}"
