name: Add new Issues to Project (Current Cycle)

on:
  issues:
    types: [opened]

permissions:
  issues: read
  repository-projects: write

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Authenticate gh
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Add issue to project
        run: |
          gh project item-add ${{ vars.PROJECT_ID }} --owner stackblitz-labs --url "${{ github.event.issue.html_url }}"
