name: Add new PRs to Project (Current Cycle)

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  contents: read
  issues: read
  pull-requests: write
  repository-projects: write

jobs:
  add:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        uses: ./.github/actions/setup-gh
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add PR to project
        run: |
          if [ -n "${{ vars.PROJECT_ID }}" ]; then
            gh project item-add ${{ vars.PROJECT_ID }} --url "${{ github.event.pull_request.html_url }}"
          else
            echo "PROJECT_ID variable not set, skipping project addition"
          fi
