name: Add new Issues to Project (Current Cycle)

on:
  issues:
    types: [opened]

permissions:
  issues: read
  repository-projects: write

jobs:
  add:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        uses: ./.github/actions/setup-gh
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add issue to project
        run: |
          if [ -n "${{ vars.PROJECT_ID }}" ]; then
            gh project item-add ${{ vars.PROJECT_ID }} --url "${{ github.event.issue.html_url }}"
          else
            echo "PROJECT_ID variable not set, skipping project addition"
          fi
